### ISSUE TITLE
Error when i try to display ColorBox

### ISSUE THREAD

**Issue by Dakistos** [enricocid/ColorBox-library#5]
I've got an error when i try to launch ColorBox

``04-24 20:40:00.053 3643-3643/morpheus.oniri E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: morpheus.oniri, PID: 3643
                                                              android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class android.widget.TextView
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                  at com.github.colorbox.ColorPickerFragment.onCreateView(ColorPickerFragment.java:123)
                                                                  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                  at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
                                                                  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                                  at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.TextView
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                              	at `android.view.LayoutInflater.rInflate(LayoutInflater.ja``

I don't what is the problem, what i forget to implement ?

**Comment by Dakistos** [comment]
Ok, my bad, i haven't instantiate my fragment :P
